id: PBD7FF2E1
initial_creation_type: input
source_metadata:
  title: Thangtong Gyalpo Series
  language: de
  description: 'Texts by and about the great siddha and bridge-builder Thangtong Gyalpo
    (thang stong rgyal po, 1361?–1485):'
  volume:
    46dc48dec6f74f35906eeab90ba16a16:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Longevity
    6e42e1be5cdb4f44b15a08a65755c36f:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Longevity
    f55a25254bbe4ecfab2d117db12ec143:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Longevity
    7ca4e9e5414a475ab4da323c21b0131c:
      title: Prayer for Dispelling Famine
      parent: Prayers
    386f4bf057014a9f80c9344a6ff9792c:
      title: Prayer of Truthful Words to Pacify the Fear of War
      parent: Prayers
    bdebd89bdc3b4a66bf3ea0c04a511918:
      title: Prayer to Thangtong Gyalpo
      parent: Prayers
    429446b3b1e14240b4d80137de99e7f2:
      title: The Outer, Inner and Secret Refuge Practice of the Mahāsiddha Thangtong
        Gyalpo
      parent: Prayers
    34d9220ef60d4f019d152990f939ab7e:
      title: 'The Verses that Saved Sakya from Sickness: A Prayer for Pacifying the
        Fear of Disease'
      parent: Prayers
    766ed08958484a8d8ffb3b0fba0ee989:
      title: Vajra Speech of the Prayer to Noble Avalokiteśvara from the Great Siddha
        Thangtong Gyalpo's Lifetime as Bhikṣu Padma Karpo
      parent: Prayers
    cabfaffea3f447a0bd163bbe900e0d67:
      title: 'Far-Reaching Benefit of Beings, Extensive as the Sky: Visualization
        and Mantra Recitation of the Great Compassionate One'
      parent: Sādhanas
created_at: '2022-03-01T01:46:09.358746'
last_modified_at: '2022-03-01T01:46:09.358749'
